--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

-- Started on 2023-05-01 14:44:38 BST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3719 (class 1262 OID 16398)
-- Name: JobSter; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "JobSter" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'C';


ALTER DATABASE "JobSter" OWNER TO postgres;

\connect "JobSter"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16423)
-- Name: Application; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Application" (
    "ApplicationId" bigint NOT NULL,
    "CoverLetter" character varying(500),
    "Resume" text,
    "ApplicationStatus" bit(1),
    "ApplicationDate" date,
    "UserID" bigint NOT NULL,
    "JobID" bigint NOT NULL,
    "UpdateDate" date
);


ALTER TABLE public."Application" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16550)
-- Name: Application_ApplicationId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Application" ALTER COLUMN "ApplicationId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Application_ApplicationId_seq"
    START WITH 10001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16447)
-- Name: Certification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Certification" (
    "CertificationID" bigint NOT NULL,
    "CertificationName" character varying(150),
    "IssuingOrganization" character varying(150),
    "IssueDate" date,
    "ExpirationDate" date,
    "CredentialID" character varying(200),
    "CredentialURL" character varying(300),
    "UserId" bigint,
    "CreateDate" date,
    "UpdateDate" date
);


ALTER TABLE public."Certification" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16551)
-- Name: Certification_CertificationID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Certification" ALTER COLUMN "CertificationID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Certification_CertificationID_seq"
    START WITH 10001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16409)
-- Name: Company; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Company" (
    "CompanyID" bigint NOT NULL,
    "CompanyName" character varying(100) NOT NULL,
    "CompanyLogo" character varying(100),
    "URL" character varying(150),
    "Email" character varying(100),
    "ComanySize" bigint,
    "CompanyDescription" character varying(10000),
    "Industry" character varying(100),
    headquarters character varying(100),
    "CreateDate" date,
    "UpdateDate" date,
    "UserId" bigint
);


ALTER TABLE public."Company" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16552)
-- Name: Company_CompanyID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Company" ALTER COLUMN "CompanyID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Company_CompanyID_seq"
    START WITH 2001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16440)
-- Name: Education; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Education" (
    "EducationID" bigint NOT NULL,
    "InstituteName" character varying(150) NOT NULL,
    degree character varying(100),
    "StartDate" date,
    "EndDate" date,
    "Grade" character(10),
    "Description" character varying(250),
    "UserId" bigint,
    "CreateDate" date,
    "UpdateDate" date
);


ALTER TABLE public."Education" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16553)
-- Name: Education_EducationID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Education" ALTER COLUMN "EducationID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Education_EducationID_seq"
    START WITH 201
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16416)
-- Name: Job; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Job" (
    "JobId" bigint NOT NULL,
    "JobTitle" character varying(100) NOT NULL,
    "JobDescription" character varying(1000),
    "JobLocation" character varying(100),
    "Salary" bigint,
    "JobType" character varying(100),
    "JabCategory" character varying(100),
    "CompanyId" bigint,
    "CreateDate" date,
    "UpdateDate" date
);


ALTER TABLE public."Job" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16469)
-- Name: JobCategory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."JobCategory" (
    "JobCategoryID" bigint NOT NULL,
    "CategoryName" character varying(100) NOT NULL,
    "CreateDate" date,
    "UpdateDate" date
);


ALTER TABLE public."JobCategory" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16555)
-- Name: JobCategory_JobCategoryID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."JobCategory" ALTER COLUMN "JobCategoryID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."JobCategory_JobCategoryID_seq"
    START WITH 1001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16464)
-- Name: JobSkill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."JobSkill" (
    "JobSkillID" bigint NOT NULL,
    "JobId" bigint NOT NULL,
    "SkillId" bigint,
    "CreateDate" date,
    "UpdateDate" date
);


ALTER TABLE public."JobSkill" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16556)
-- Name: JobSkill_JobSkillID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."JobSkill" ALTER COLUMN "JobSkillID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."JobSkill_JobSkillID_seq"
    START WITH 101
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16614)
-- Name: JobType; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."JobType" (
    "JobTypeId" bigint NOT NULL,
    "TypeName" character varying(25)
);


ALTER TABLE public."JobType" OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16617)
-- Name: JobType_JobTypeId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."JobType" ALTER COLUMN "JobTypeId" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."JobType_JobTypeId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16554)
-- Name: Job_JobId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Job" ALTER COLUMN "JobId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Job_JobId_seq"
    START WITH 100043
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16454)
-- Name: Language; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Language" (
    "LanguageID" bigint NOT NULL,
    "LanguageName" character varying(200),
    "ProficiencyLevel" character varying(100),
    "CreateDate" date,
    "UpdateDate" date,
    "UserID" bigint
);


ALTER TABLE public."Language" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16557)
-- Name: Language_LanguageID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Language" ALTER COLUMN "LanguageID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Language_LanguageID_seq"
    START WITH 10
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16404)
-- Name: Role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Role" (
    "RoleID" bigint NOT NULL,
    "RoleName" character varying(50) NOT NULL,
    "CreateDate" date,
    "UpdateDate" date
);


ALTER TABLE public."Role" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16558)
-- Name: Role_RoleID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Role" ALTER COLUMN "RoleID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Role_RoleID_seq"
    START WITH 10
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16430)
-- Name: Skill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Skill" (
    "SkillId" bigint NOT NULL,
    "skillName" character varying(100),
    "CreateDate" date,
    "UpdateDate" date
);


ALTER TABLE public."Skill" OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16559)
-- Name: Skill_SkillId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Skill" ALTER COLUMN "SkillId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Skill_SkillId_seq"
    START WITH 10
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16399)
-- Name: User; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User" (
    "UserId" bigint NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100),
    "Email" character varying(100) NOT NULL,
    "Mobile" character varying(12),
    password character varying(50) NOT NULL,
    "CreateDate" date,
    "UpdateDATe" date,
    "RoleID" bigint
);


ALTER TABLE public."User" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16459)
-- Name: UserLanguage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserLanguage" (
    "UserLanguageID" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "LanguageId" bigint,
    "CreateDate" date,
    "UpdateDate" date
);


ALTER TABLE public."UserLanguage" OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16561)
-- Name: UserLanguage_UserLanguageID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserLanguage" ALTER COLUMN "UserLanguageID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserLanguage_UserLanguageID_seq"
    START WITH 10
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16435)
-- Name: UserSkill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserSkill" (
    "UserSkillID" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "SkillId" bigint NOT NULL,
    "ExperienceLevel" character varying(100),
    "CreateDate" date,
    "UpdateDate" date
);


ALTER TABLE public."UserSkill" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16562)
-- Name: UserSkill_UserSkillID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserSkill" ALTER COLUMN "UserSkillID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserSkill_UserSkillID_seq"
    START WITH 1001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16560)
-- Name: User_UserId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."User" ALTER COLUMN "UserId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_UserId_seq"
    START WITH 30001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3690 (class 0 OID 16423)
-- Dependencies: 218
-- Data for Name: Application; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3694 (class 0 OID 16447)
-- Dependencies: 222
-- Data for Name: Certification; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3688 (class 0 OID 16409)
-- Dependencies: 216
-- Data for Name: Company; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3693 (class 0 OID 16440)
-- Dependencies: 221
-- Data for Name: Education; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3689 (class 0 OID 16416)
-- Dependencies: 217
-- Data for Name: Job; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3698 (class 0 OID 16469)
-- Dependencies: 226
-- Data for Name: JobCategory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."JobCategory" VALUES (1001, 'Project Manager', NULL, NULL);
INSERT INTO public."JobCategory" VALUES (1002, 'Software Engineer', NULL, NULL);
INSERT INTO public."JobCategory" VALUES (1003, 'Technology Team Leader', NULL, NULL);
INSERT INTO public."JobCategory" VALUES (1004, 'Web Developer', NULL, NULL);
INSERT INTO public."JobCategory" VALUES (1005, 'Databae Adminstrator', NULL, NULL);


--
-- TOC entry 3697 (class 0 OID 16464)
-- Dependencies: 225
-- Data for Name: JobSkill; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3712 (class 0 OID 16614)
-- Dependencies: 240
-- Data for Name: JobType; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."JobType" OVERRIDING SYSTEM VALUE VALUES (1, 'Full time');
INSERT INTO public."JobType" OVERRIDING SYSTEM VALUE VALUES (2, 'Part Time');
INSERT INTO public."JobType" OVERRIDING SYSTEM VALUE VALUES (3, 'Hybrid');
INSERT INTO public."JobType" OVERRIDING SYSTEM VALUE VALUES (4, 'Remote');


--
-- TOC entry 3695 (class 0 OID 16454)
-- Dependencies: 223
-- Data for Name: Language; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Language" VALUES (10, 'English', 'Excellent', NULL, NULL, NULL);
INSERT INTO public."Language" VALUES (11, 'English', 'Medium', NULL, NULL, NULL);
INSERT INTO public."Language" VALUES (12, 'English', 'Basic', NULL, NULL, NULL);
INSERT INTO public."Language" VALUES (13, 'Hindi', 'Excellent', NULL, NULL, NULL);
INSERT INTO public."Language" VALUES (14, 'Hindi', 'Medium', NULL, NULL, NULL);
INSERT INTO public."Language" VALUES (15, 'Hindi', 'Basic', NULL, NULL, NULL);


--
-- TOC entry 3687 (class 0 OID 16404)
-- Dependencies: 215
-- Data for Name: Role; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Role" VALUES (10, 'Applicant', NULL, NULL);
INSERT INTO public."Role" VALUES (11, 'Employer', NULL, NULL);
INSERT INTO public."Role" VALUES (12, 'Admin', NULL, NULL);


--
-- TOC entry 3691 (class 0 OID 16430)
-- Dependencies: 219
-- Data for Name: Skill; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Skill" VALUES (10, 'Java', NULL, NULL);
INSERT INTO public."Skill" VALUES (11, '.net', NULL, NULL);
INSERT INTO public."Skill" VALUES (12, 'SQL Server', NULL, NULL);
INSERT INTO public."Skill" VALUES (13, 'React', NULL, NULL);
INSERT INTO public."Skill" VALUES (14, 'Oracle DB', NULL, NULL);
INSERT INTO public."Skill" VALUES (15, 'PHP', NULL, NULL);
INSERT INTO public."Skill" VALUES (16, 'Java Script', NULL, NULL);
INSERT INTO public."Skill" VALUES (17, 'Type Script', NULL, NULL);
INSERT INTO public."Skill" VALUES (18, 'Anglar', NULL, NULL);


--
-- TOC entry 3686 (class 0 OID 16399)
-- Dependencies: 214
-- Data for Name: User; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."User" VALUES (30001, 'Admin', NULL, 'neerajprayag@gmail.com', '7442779526', 'admin', NULL, NULL, NULL);


--
-- TOC entry 3696 (class 0 OID 16459)
-- Dependencies: 224
-- Data for Name: UserLanguage; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3692 (class 0 OID 16435)
-- Dependencies: 220
-- Data for Name: UserSkill; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3720 (class 0 OID 0)
-- Dependencies: 227
-- Name: Application_ApplicationId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Application_ApplicationId_seq"', 10001, false);


--
-- TOC entry 3721 (class 0 OID 0)
-- Dependencies: 228
-- Name: Certification_CertificationID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Certification_CertificationID_seq"', 10001, false);


--
-- TOC entry 3722 (class 0 OID 0)
-- Dependencies: 229
-- Name: Company_CompanyID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Company_CompanyID_seq"', 2001, false);


--
-- TOC entry 3723 (class 0 OID 0)
-- Dependencies: 230
-- Name: Education_EducationID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Education_EducationID_seq"', 201, false);


--
-- TOC entry 3724 (class 0 OID 0)
-- Dependencies: 232
-- Name: JobCategory_JobCategoryID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."JobCategory_JobCategoryID_seq"', 1005, true);


--
-- TOC entry 3725 (class 0 OID 0)
-- Dependencies: 233
-- Name: JobSkill_JobSkillID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."JobSkill_JobSkillID_seq"', 101, false);


--
-- TOC entry 3726 (class 0 OID 0)
-- Dependencies: 241
-- Name: JobType_JobTypeId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."JobType_JobTypeId_seq"', 4, true);


--
-- TOC entry 3727 (class 0 OID 0)
-- Dependencies: 231
-- Name: Job_JobId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Job_JobId_seq"', 100043, false);


--
-- TOC entry 3728 (class 0 OID 0)
-- Dependencies: 234
-- Name: Language_LanguageID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Language_LanguageID_seq"', 15, true);


--
-- TOC entry 3729 (class 0 OID 0)
-- Dependencies: 235
-- Name: Role_RoleID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Role_RoleID_seq"', 12, true);


--
-- TOC entry 3730 (class 0 OID 0)
-- Dependencies: 236
-- Name: Skill_SkillId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Skill_SkillId_seq"', 18, true);


--
-- TOC entry 3731 (class 0 OID 0)
-- Dependencies: 238
-- Name: UserLanguage_UserLanguageID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."UserLanguage_UserLanguageID_seq"', 10, false);


--
-- TOC entry 3732 (class 0 OID 0)
-- Dependencies: 239
-- Name: UserSkill_UserSkillID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."UserSkill_UserSkillID_seq"', 1001, false);


--
-- TOC entry 3733 (class 0 OID 0)
-- Dependencies: 237
-- Name: User_UserId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."User_UserId_seq"', 30001, true);


--
-- TOC entry 3513 (class 2606 OID 16429)
-- Name: Application Application_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Application"
    ADD CONSTRAINT "Application_pkey" PRIMARY KEY ("ApplicationId");


--
-- TOC entry 3521 (class 2606 OID 16453)
-- Name: Certification Certification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Certification"
    ADD CONSTRAINT "Certification_pkey" PRIMARY KEY ("CertificationID");


--
-- TOC entry 3509 (class 2606 OID 16415)
-- Name: Company Company_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Company"
    ADD CONSTRAINT "Company_pkey" PRIMARY KEY ("CompanyID");


--
-- TOC entry 3519 (class 2606 OID 16446)
-- Name: Education Education_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Education"
    ADD CONSTRAINT "Education_pkey" PRIMARY KEY ("EducationID");


--
-- TOC entry 3529 (class 2606 OID 16473)
-- Name: JobCategory JobCategory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."JobCategory"
    ADD CONSTRAINT "JobCategory_pkey" PRIMARY KEY ("JobCategoryID");


--
-- TOC entry 3527 (class 2606 OID 16468)
-- Name: JobSkill JobSkill_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."JobSkill"
    ADD CONSTRAINT "JobSkill_pkey" PRIMARY KEY ("JobSkillID");


--
-- TOC entry 3531 (class 2606 OID 16619)
-- Name: JobType JobType_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."JobType"
    ADD CONSTRAINT "JobType_pkey" PRIMARY KEY ("JobTypeId");


--
-- TOC entry 3511 (class 2606 OID 16422)
-- Name: Job Job_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Job"
    ADD CONSTRAINT "Job_pkey" PRIMARY KEY ("JobId");


--
-- TOC entry 3523 (class 2606 OID 16458)
-- Name: Language Language_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Language"
    ADD CONSTRAINT "Language_pkey" PRIMARY KEY ("LanguageID");


--
-- TOC entry 3507 (class 2606 OID 16408)
-- Name: Role Role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Role"
    ADD CONSTRAINT "Role_pkey" PRIMARY KEY ("RoleID");


--
-- TOC entry 3515 (class 2606 OID 16434)
-- Name: Skill Skill_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Skill"
    ADD CONSTRAINT "Skill_pkey" PRIMARY KEY ("SkillId");


--
-- TOC entry 3525 (class 2606 OID 16463)
-- Name: UserLanguage UserLanguage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserLanguage"
    ADD CONSTRAINT "UserLanguage_pkey" PRIMARY KEY ("UserLanguageID");


--
-- TOC entry 3517 (class 2606 OID 16439)
-- Name: UserSkill UserSkill_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserSkill"
    ADD CONSTRAINT "UserSkill_pkey" PRIMARY KEY ("UserSkillID");


--
-- TOC entry 3505 (class 2606 OID 16403)
-- Name: User User_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY ("UserId");


--
-- TOC entry 3543 (class 2606 OID 16594)
-- Name: JobSkill JOBID_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."JobSkill"
    ADD CONSTRAINT "JOBID_FK" FOREIGN KEY ("JobId") REFERENCES public."Job"("JobId") NOT VALID;


--
-- TOC entry 3535 (class 2606 OID 16569)
-- Name: Application JOB_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Application"
    ADD CONSTRAINT "JOB_FK" FOREIGN KEY ("JobID") REFERENCES public."Job"("JobId") NOT VALID;


--
-- TOC entry 3534 (class 2606 OID 16589)
-- Name: Job JobComId_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Job"
    ADD CONSTRAINT "JobComId_FK" FOREIGN KEY ("CompanyId") REFERENCES public."Company"("CompanyID") NOT VALID;


--
-- TOC entry 3532 (class 2606 OID 16620)
-- Name: User RoleID_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "RoleID_FK" FOREIGN KEY ("RoleID") REFERENCES public."Role"("RoleID") NOT VALID;


--
-- TOC entry 3537 (class 2606 OID 16609)
-- Name: UserSkill SkilUser_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserSkill"
    ADD CONSTRAINT "SkilUser_FK" FOREIGN KEY ("UserId") REFERENCES public."User"("UserId") NOT VALID;


--
-- TOC entry 3541 (class 2606 OID 16599)
-- Name: Language USERIDLang_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Language"
    ADD CONSTRAINT "USERIDLang_FK" FOREIGN KEY ("UserID") REFERENCES public."User"("UserId") NOT VALID;


--
-- TOC entry 3533 (class 2606 OID 16579)
-- Name: Company UserCOMP_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Company"
    ADD CONSTRAINT "UserCOMP_FK" FOREIGN KEY ("UserId") REFERENCES public."User"("UserId") NOT VALID;


--
-- TOC entry 3540 (class 2606 OID 16574)
-- Name: Certification UserCert_Fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Certification"
    ADD CONSTRAINT "UserCert_Fk" FOREIGN KEY ("UserId") REFERENCES public."User"("UserId") NOT VALID;


--
-- TOC entry 3539 (class 2606 OID 16584)
-- Name: Education UserIDEDU_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Education"
    ADD CONSTRAINT "UserIDEDU_FK" FOREIGN KEY ("UserId") REFERENCES public."User"("UserId") NOT VALID;


--
-- TOC entry 3542 (class 2606 OID 16604)
-- Name: UserLanguage UserLang_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserLanguage"
    ADD CONSTRAINT "UserLang_FK" FOREIGN KEY ("UserId") REFERENCES public."User"("UserId") NOT VALID;


--
-- TOC entry 3536 (class 2606 OID 16564)
-- Name: Application User_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Application"
    ADD CONSTRAINT "User_FK" FOREIGN KEY ("UserID") REFERENCES public."User"("UserId") NOT VALID;


--
-- TOC entry 3538 (class 2606 OID 16625)
-- Name: UserSkill User_FK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserSkill"
    ADD CONSTRAINT "User_FK" FOREIGN KEY ("SkillId") REFERENCES public."Skill"("SkillId") NOT VALID;


-- Completed on 2023-05-01 14:44:38 BST

--
-- PostgreSQL database dump complete
--

